### ISSUE TITLE
Possible bug in conversion from gas to power in GasTurbine rules?

### ISSUE THREAD

**Issue by sondreew** [oogeso/oogeso#106]
In the following code, `gas_energy_content` is multiplied into `lhs`.  `rhs`, however, gets the gas volume input from the `A` and `B` coefficients related to the turbine efficiency. 

https://github.com/oogeso/oogeso/blob/8cb50dc4d3cac280565fbdd1b9640fffe0133727/src/oogeso/core/devices/gasturbine.py#L26-L44

As far as I understand, with `model.varDeviceFlow[dev, "gas", "in", t]` being volume per time, `gas_energy_content` being energy per volume, `A` being volume per (time and power), and `B` being volume per time, (and hence `fuel` being volume per time), the following seems to be defined:

`lhs = `  ((volume / time) * energy/volume) / (power) = 1

`rhs =`  volume / time + (volume / (time * power) * volume) / power = volume / time + (volume / power)^2 * 1 / time

As `P_max` only shows up in the last term of `rhs`, the two terms here seem to not represent the same thing, and `lhs` seems to represent a quantity different from both of them.

Removing `gas_energy_content` and `P_max` everywhere yields both `lhs` and `rhs` representing volume / time. This further yields the expected relationship between the values on the edges in and out of the device, as well as calculated co2 emissions (Given all variables with the units assumed above).

**Comment by HaraldGSvendsen** [comment]
This is not a bug. The A and B parameters are dimensionless parameters. The docs are a bit confusing but
