### ISSUE TITLE
Let path to solver executable be optional input argument from user

### ISSUE THREAD

**Issue by frodehk** [oogeso/oogeso#69]
It is a potential challenge to set up the link to the solver in rgs/Linux. It is possible to specify the path to the executable directly as an optional second argument in the SolverFactory object (pyomo.environ) in the OptimizationModel-class.

**Comment by HaraldGSvendsen** [comment]
Yes, I think this is a good idea and should be quite easy to implement.

Suggest including it as an argument in the same way as solver is specified, i.e. 
Simulator.run_simulation(solver="cbc", solver_path=None,...)
OptimisationModel.solve(solver="cbc",solver_path=None,...)

**Comment by frodehk** [comment]
I agree, that is even better.
